"""initial schema

Revision ID: 33169b2f9300
Revises: 
Create Date: 2026-04-18 19:26:46.755275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('inscricao_municipal', sa.String(length=15), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=60), nullable=True),
    sa.Column('cert_path', sa.String(length=255), nullable=True),
    sa.Column('cert_senha_enc', sa.String(length=512), nullable=True),
    sa.Column('cert_validade', sa.Date(), nullable=True),
    sa.Column('cert_cnpj', sa.String(length=14), nullable=True),
    sa.Column('cert_cn', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cnpj'), ['cnpj'], unique=True)

    op.create_table('agendamentos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('diario', 'semanal', 'mensal', name='tipoagendamento', native_enum=False), nullable=False),
    sa.Column('dia_execucao', sa.SmallInteger(), nullable=True),
    sa.Column('hora_execucao', sa.Time(), nullable=False),
    sa.Column('periodo_retroativo_dias', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultima_execucao', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('cn', sa.String(length=255), nullable=True),
    sa.Column('cnpj_certificado', sa.String(length=14), nullable=True),
    sa.Column('validade_inicio', sa.Date(), nullable=True),
    sa.Column('validade_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('periodo_emissao', 'periodo_competencia', 'faixa', 'rps', name='tipoconsulta', native_enum=False), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('metodo_ws', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'processando', 'sucesso', 'erro', name='statusconsulta', native_enum=False), nullable=False),
    sa.Column('total_notas', sa.Integer(), nullable=False),
    sa.Column('total_paginas', sa.Integer(), nullable=False),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('xml_request', sa.Text(), nullable=True),
    sa.Column('xml_response_sample', sa.Text(), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfse_xmls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cliente_id', sa.String(length=36), nullable=False),
    sa.Column('consulta_id', sa.String(length=36), nullable=True),
    sa.Column('numero_nfse', sa.String(length=15), nullable=False),
    sa.Column('codigo_verificacao', sa.String(length=20), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.Column('competencia', sa.Date(), nullable=True),
    sa.Column('valor_servicos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_iss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cnpj_prestador', sa.String(length=14), nullable=True),
    sa.Column('cnpj_tomador', sa.String(length=14), nullable=True),
    sa.Column('razao_social_tomador', sa.String(length=150), nullable=True),
    sa.Column('item_lista_servico', sa.String(length=5), nullable=True),
    sa.Column('status_nfse', sa.SmallInteger(), nullable=False),
    sa.Column('xml_path', sa.String(length=255), nullable=False),
    sa.Column('xml_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'numero_nfse', name='uq_nfse_cliente_numero')
    )
    with op.batch_alter_table('nfse_xmls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfse_xmls_competencia'), ['competencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfse_xmls_data_emissao'), ['data_emissao'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfse_xmls_numero_nfse'), ['numero_nfse'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfse_xmls_xml_hash'), ['xml_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfse_xmls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfse_xmls_xml_hash'))
        batch_op.drop_index(batch_op.f('ix_nfse_xmls_numero_nfse'))
        batch_op.drop_index(batch_op.f('ix_nfse_xmls_data_emissao'))
        batch_op.drop_index(batch_op.f('ix_nfse_xmls_competencia'))

    op.drop_table('nfse_xmls')
    op.drop_table('consultas')
    op.drop_table('certificados')
    op.drop_table('agendamentos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_cnpj'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
