"""add alertas table

Revision ID: c22edfa1fa54
Revises: 0001_initial
Create Date: 2026-04-18 19:34:05.906366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_alertas'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('resolvido', sa.Boolean(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_tipo'))

    op.drop_table('alertas')
    # ### end Alembic commands ###
